### ISSUE TITLE
Closures

### ISSUE THREAD

**Issue by crisdosaygo** [yuwu9145/nest-object-deep-copy#7]
Should surface the limitation that closures cannot be copied because the closed over scope is inaccessible and unserializable. 

Otherwise this is good!

If you want to see an example of where I handle bigints, date objects, and other edge cases check out [weird-json](https://github.com/i5ik/weird-json)

**Comment by yuwu9145** [comment]
Hi @i5ik ,

If following test case covers the closure senario that you are thinking about, it has been already supported:

```javascript
describe('Closures', () => {
  it('should keep closures', () => {
    const user = {
      name: 'User 1',
      speak: function () {
        function speakWithMic(name) {
          return 'My name is ' + name + ' and I speak with Mic';
        }
        return speakWithMic(this.name);
      },
    };

    const newUser = deepCopy(user);
    newUser.name = 'User 2';

    expect(user.speak()).toBe('My name is User 1 and I speak with Mic');
    expect(newUser.speak()).toBe('My name is User 2 and I speak with Mic');
  });
});
```

BTW, I found [weird-json](https://github.com/i5ik/weird-json) is interesting and I will spend some time on playing around it.

Thanks for sharing it.

Greetings from Yuchao :)

**Comment by crisdosaygo** [comment]
Hey Yuchao :)

I was thinking more along the lines of:

```js
describe('Closures', () => {
  it('should keep closures', () => {
    const firstName = 'Heg';

    function userSpeak() {
      return `My name is ${firstName} and I speak with Mig`
    }
   
    const newUserSpeak = deepClone(userSpeak);

    expect(userSpeak()).toBe('My name is Heg and I speak with Mig');
    expect(newUserSpeak()).toBe('My name is Heg and I speak with Mig');
  });
});
```

**Comment by yuwu9145** [comment]
Functions look more like a procedure value, what would be a real use case that requires deep clone a function? 

In above test case, looks like two functions are doing the same thing.

**Comment by i5ik** [comment]
Ah, I think I see what you're saying, you don't see any use case for deep cloning of functions because you may as well just pass them around by reference, and if you want to create a new function or closure, just invoke the parent function. That's fair enough. I was coming at it from the "serialize" point of view, but I see your use case doesn't need that. All good then!

**Comment by crisdosaygo** [comment]
> Functions look more like a procedure value, what would be a real use case that requires deep clone a function?
> 
> In above test case, looks like two functions are doing the same thing.

😂 Sounds like you think my example is no good, but just remember, I based it on your example, so if you think it's no good then that's on you. 😆 😂 

But I guess you're just coming at it from a different perspective...I think I now see what you're saying, you don't see any use case for deep cloning of functions because you may as well just pass them around by reference, and if you want to create a new function or closure, just invoke the parent function. That's fair enough. I was coming at it from the "serialize" point of view, but I see your use case doesn't need that. All good then!

**Comment by yuwu9145** [comment]
I provided the initial example for clusure purpose only. Since I am not sure what use case does function cloning serve, that's why I am asking for it. Because "cloning" should be something like "**Get a copy from original thing but can use the copy do something different**" and I cannot think of a senario that "pure function cloning" does this.

In addition, it doesn't do any serialisation but just treat function as a "procedure value" and assign it to new cloned object. However this does not affect two functions serve their parent objects respectively, invoking them they will have separate state and `this`.

**Comment by crisdosaygo** [comment]
Yep that's what i thought your view was. Thanks for sharing! 😊
